openapi: 3.0.3
info:
  title: GirigiriMeshi
  description: |-
    ギリギリで駆け込める飯屋を探してギリギリで駆け込もう
  version: 0.1.0
tags:
  - name: restaurant
    description: Everything about nearby restaurants
paths:
  /restaurants:
    post:
      tags:
        - restaurant
      summary: Search for nearby restaurant
      description: Get a list of nearby restaurants from location
      operationId: getRestaurants
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Location'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
        '500':
          description: Internal server error
components:
  schemas:
    Location:
      type: object
      required:
        - latitude
        - longitude
      properties:
        latitude:
          description: 緯度
          type: number
          format: double
          example: 35.5827517
        longitude:
          description: 経度
          type: number
          format: double
          example: 140.1327256
    Restaurant:
      type: object
      required:
        - name
        - location
        - closeTime
        - placeId
      properties: 
        name:
          type: string
          description: name of the restaurant
          example: 鐵 蘇我本店
        location:
          $ref: '#/components/schemas/Location'
        closeTime:
          type: string
          format: date-time
        placeId:
          type: string
          example: ChIJeSTaRQWbImARznMsCGVeYcw
          description: This id is based on Google Places API
        photoUrl:
          type: string
          example: https://lh3.googleusercontent.com/places/AJDFj40BrNvrjCwyFnyutzhWTBod6mrELN7sABx13W1H2pFs0ImIqrrtBaI5n_LQBMRvqdkybqkj8qCdtNwiCbfNsgAkUbkvs5luiMA=s1600-w1000
        rating:
          type: number
          format: double
          example: 3.7
