import Head from "next/head";
import React, { useState, useEffect } from "react";

import { GetPosition } from "../model/Position";
import { Shops, FetchShops } from "../model/Shops";
import ShopCardList from "../components/ShopCardList";

export default function Home() {
    console.log("index render start");

    const [shopList, setShopList] = useState<Shops>([]);
    const [isLoaded, setIsLoaded] = useState<boolean>(false);
    const [error, setError] = useState<string>("");

    useEffect(() => {
        (async () => {
            const nowUserPosition = await GetPosition().catch((error) => {
                setError(error);
                return null;
            });
            if (nowUserPosition === null) {
                return;
            }

            const shops = await FetchShops(nowUserPosition).catch((error) => {
                setError(error);
                return null;
            });
            if (shops === null) {
                return;
            }

            setShopList(shops);
            setIsLoaded(true);
        })();
    }, []);

    if (!isLoaded) {
        return <div>Loading...</div>;
    }

    if (error) {
        return <div>Error: {error}</div>;
    }

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ShopCardList shopList={shopList}></ShopCardList>
        </div>
    );
}
