name: Build Frontend
on:
  push:
    branches-ignore:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        working-directory: ./frontend

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
        working-directory: ./frontend

      - name: cache-node-modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        working-directory: ./frontend

      - name: Install Dependencies
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install
        working-directory: ./frontend

      - name: Build Application
        run: yarn build
        working-directory: ./frontend
